### ISSUE TITLE
Handlebars doesnt apply key

### ISSUE THREAD

**Issue by vaseker** [catberry/catberry-l10n-handlebars-helper#1]
Hello!
I want translations on my app, so I've include `catberry-l10n` & `catberry-l10n-handlebars-helper` packages.

In both have strange behavior:
- Just `catberry-l10n`: have 2 components `login` and `register`, both have keys `login` and `password` plus some different keys. I defined in component's .js file, in `render` method, assigning of l10n (based on your sample) hash like this: 

``` js
Login.prototype.render = function () {
  var locale = this._l10n.getCurrentLocale(this.$context);
  return { 
    l10n: {
      login: this._l10n.get(locale, 'login'),
      password: this._l10n.get(locale, 'password')
}
```

``` js
Register.prototype.render = function () {
  var locale = this._l10n.getCurrentLocale(this.$context);
  return { 
    l10n: {
      login: this._l10n.get(locale, 'login'),
      password: this._l10n.get(locale, 'password'),
      firstname: this._l10n.get(locale, 'firstname'),
      lastname: this._l10n.get(locale, 'lastname') 
}
```

Then, if I open page with `login` component then page with `register` component, it will be rendered with `login` component keys. And method `render` calls only on first of these components. Looks like them are rendered with result of first accessed method `.render()`. It'n normal behavior? How can aviod this?
- ~~Then I found `catberry-l10n-handlebars-helper` and its sample in `catberry-homepage`. Grabbed `lib/componentBase.js`, configured browser and server bundles, inherited problem components from `base`, updated templates `{{l10n.login}}` >> `{{{l10n login}}}`. And have got `''` values for all keys (from https://github.com/catberry/catberry-l10n-handlebars-helper/blob/develop/lib/LocalizationHelper.js#L79). Looks like handlebars doesnt call helper with key argument. I have a sample of this on http://88.198.53.113:3001/login. This build logs to console `arguments` hash of `HandlebarsHelper` calls.~~

My bad. Calling translation with undef variables instead of string keys.
`{{{l10n login}}}` >> `{{{l10n "login"}}}`

Usage sample:
https://github.com/vaseker/netbuyer/blob/master/catberry_components/page-registration/index.js

ЧЯДНТ?

Thanks.

**Comment by rdner** [comment]
As I understood, the problem is that your localization keys are not unique.
`catberry-l10n` package doesn't deal with name collisions. All localization keys should be unique across all components. Otherwise, the value will be shown from the last loaded component.

Therefore, I recommend you to use a prefix with the name of the component.

For example `COMPONENT_KEY`.

**Comment by vaseker** [comment]
No, I haven't keys collisions

Yep, I should apply some key naming conventions.

**Comment by rdner** [comment]
But according your example, component `login` has `login` and `password` localization keys and component `registration` has the same keys `login` and `password`.

> ... then page with register component, it will be rendered with login component keys

The behaviour you described is a result of a collision.
Or I got it wrong?

**Comment by vaseker** [comment]
Yes, them uses some same keys, but these localizations defined once, in one
root lang.json

Maybe I will build this case example?
14 июня 2015 г. 3:07 PM пользователь "Denis Rechkunov" <
notifications@github.com> написал:

**Comment by rdner** [comment]
Also, you should return `locale` field in the data object from `render` method. Otherwise the default localization will be used.

**Comment by rdner** [comment]
> And method render calls only on first of these components. Looks like them are rendered with result of first accessed method .render(). It'n normal behavior? How can aviod this?

I reproduced the problem, you were talking about. Investigating...

**Comment by rdner** [comment]
Ok, I've got the reason.

I found the template of the `page` component.

``` html
<cat-page-{{currentPage}} id="pages-current"></cat-page-{{currentPage}}>
```

So, it sets the same ID every time for different components, which is not good.
Catberry confuses these components because there is only one way to distinct the components – ID.
So, you can easily fix it using the template below:

``` html
<cat-page-{{currentPage}} id="pages-current-{{currentPage}}"></cat-page-{{currentPage}}>
```

**Comment by vaseker** [comment]
Got it. Thanks.
14 июня 2015 г. 3:34 PM пользователь "Denis Rechkunov" <
notifications@github.com> написал:
